/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Marco Ladu
 * Created: 23-mag-2017
 */

-- db ammdb user: amm psw: amm

CREATE TABLE utenti(
    utenti_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utenti_nome VARCHAR(50),
    utenti_cognome VARCHAR(50),
    utenti_urlImg VARCHAR(100),
    utenti_frase VARCHAR(300),
    utenti_data VARCHAR(15),
    utenti_password VARCHAR(20)
);

CREATE TABLE post(
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_idProprietario INTEGER,
    FOREIGN KEY (post_idProprietario) REFERENCES utenti(utenti_id),
    post_idBacheca INTEGER,
    post_text VARCHAR(1024),
    post_img VARCHAR(100),
    post_link VARCHAR(100)
);

CREATE TABLE gruppi(
    gruppi_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gruppi_nome VARCHAR(50)
);

CREATE TABLE utenti_gruppi(
    u_g_idUtente INTEGER,
    FOREIGN KEY (u_g_idUtente) REFERENCES utenti(utenti_id),
    u_g_idGruppo INTEGER,
    FOREIGN KEY (u_g_idGruppo) REFERENCES gruppi(gruppi_id)
);

--Popolamento utenti

INSERT INTO utenti (utenti_id, utenti_nome, utenti_cognome, utenti_urlImg, utenti_frase, utenti_data, utenti_password)
VALUES (default,
        'cthulhu',
        'il Grande Antico',
        'IMG/cthulhu.jpg',
        'Hail Cthulhu',
        '0000-12-25',
        '1234');

INSERT INTO utenti (utenti_id, utenti_nome, utenti_cognome, utenti_urlImg, utenti_frase, utenti_data, utenti_password)
VALUES (default,
        'chewbacca',
        'Wookiee',
        'IMG/chewbacca.jpg',
        'Uuuuuuuuur',
        '1970-06-12',
        '1234');

INSERT INTO utenti (utenti_id, utenti_nome, utenti_cognome, utenti_urlImg, utenti_frase, utenti_data, utenti_password)
VALUES (default,
        'salvatore',
        'Aranzulla',
        'IMG/aranzulla.jpg',
        'Ti guiderò nella vastità delle mie guide',
        '1990-02-24',
        '1234');

INSERT INTO utenti (utenti_id, utenti_nome, utenti_urlImg, utenti_password)
VALUES (default,
        'utente',
        'IMG/incompleto.png',
        '1234');

--Popolamento Post

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text)
VALUES (default,
        1,
        1,
        'Ph nglui mglw nafh Cthulhu R lyeh wgah nagl fhtagn');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text, post_img)
VALUES (default,
        2,
        2,
        'Uuuuuuuuur Ahhhrrrrrrrr Uhrrrrr Ahhhrrrrrrrr Ahrgggg :(',
        'IMG/hansolo.png');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text, post_link)
VALUES (default,
        3,
        3,
        'Ed ecco la guida definitiva!',
        'https://www.aranzulla.it/');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text, post_img)
VALUES (default,
        1,
        1,
        'MMMMMMMMmmm che buona!!',
        'IMG/img1.jpg');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text)
VALUES (default,
        1,
        1,
        'Oggi ho prorpio voglia di distruggere il mondo!!');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text)
VALUES (default,
        2,
        2,
        'aaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrr');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text, post_img)
VALUES (default,
        2,
        2,
        ':D',
        'IMG/img2.jpg');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text, post_img)
VALUES (default,
        3,
        3,
        'Troppo forte!!',
        'IMG/img3.png');

INSERT INTO post (post_id, post_idProprietario, post_idBacheca, post_text)
VALUES (default,
        4,
        4,
        'Non ho il profilo completo :(');

--Popolamento gruppi

INSERT INTO gruppi (gruppi_id, gruppi_nome)
VALUES (default,
        'L anima oscura');

INSERT INTO gruppi (gruppi_id, gruppi_nome)
VALUES (default,
        'CS:GO ITA');
